version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    directory: "/"
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Location of submodules in the repository, usually the root
    schedule:
      interval: "daily" # Check for updates daily
